version: "3.9"
services:
  ts_app_1:
    image: timesheets:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DEFAULT_USERNAME: admin
      VAULT_TOKEN: myroot
      VAULT_HOST: ts_vault
  ts_app_2:
    image: timesheets:boot
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DEFAULT_USERNAME: admin
      VAULT_TOKEN: myroot
      VAULT_HOST: ts_vault
  ts_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: jmix
      POSTGRES_PASSWORD: jmix
      POSTGRES_DB: ts_compose_db
  ts_vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
    ports:
      - "8200:8200"
  nginx:
    image: nginx
    ports:
      - "8084:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro